version: '3.9'

services:
  web-client:
    context: ./frontend-client/
    dockerfile: Dockerfile
    ports:
      - "80:80"

  orchestrator:
    context: ./orchestrator/
    dockerfile: Dockerfile
    ports:
      - "8000:8000"

  language-generator:
    context: ./language-generator/
    dockerfile: Dockerfile
    ports:
      - "8001:8000"
