version: '3.9'

services:
  web-client:
    build:
      context: ./frontend-client/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      
  orchestrator:
    build:
      context: ./orchestrator/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
        
  language-generator:
    build:
      context: ./language-generator/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"

      
  diagram-generator:
    build:
      context: ./diagram-generator/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8002:8002"

      
  software-generator:
    build:
      context: ./software-generator/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8003:8003"

  rabbitmq:
    build:
      context: ./rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP protocol for clients
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    restart: unless-stopped

volumes:
  rabbitmq_data:
