version: '3.9'

services:
  web-client:
    build:
      context: ./frontend-client/
      dockerfile: Dockerfile
    depends_on:
      - orchestrator
    ports:
      - "80:80"
      
  orchestrator:
    build:
      context: ./orchestrator/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"

  language-agent:
    build:
      context: ./language-agent/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - orchestrator
    ports:
      - "8011:8011"

  diagram-agent:
    build:
      context: ./diagram-agent/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - orchestrator
    ports:
      - "8012:8012"

  software-agent:
    build:
      context: ./software-agent/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - orchestrator
    ports:
      - "8013:8013"
        
  language-generator:
    build:
      context: ./language-generator/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - language-agent
    ports:
      - "8001:8001"

      
  diagram-generator:
    build:
      context: ./diagram-generator/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - diagram-agent
    ports:
      - "8002:8002"

      
  software-generator:
    build:
      context: ./software-generator/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - software-agent
    ports:
      - "8003:8003"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP protocol
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
