version: '3.9'

services:
  web-client:
    build:
      context: ./frontend-client/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      
  orchestrator:
    build:
      context: ./orchestrator/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
        
  language-generator:
    build:
      context: ./language-generator/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"
